
# Especifica el SO y la distribución a usar
arch: amd64
os: linux
dist: xenial

# Especifica que se va a usar docker
services:
    - docker

# Descarga la imagen y la ejecuta
script:
    - docker run -t -v $TRAVIS_BUILD_DIR:/test rauldpm/test-iv-kotlin

after_success: true

before_deploy:
    - git config --global user.email "builds@travis-ci.com"
    - git config --global user.name "Travis CI"
    - export GIT_TAG=$TRAVIS_BRANCH-v0.1.$TRAVIS_BUILD_NUMBER
    - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER" --force
    - git push -q https://"$TOKEN_GH"@github.com/rauldpm/IV-Heroku-Test-Kotlin --tags

deploy:
    - provider: releases
      token: "$TOKEN_GH"
      file: 
        - app/build/libs/app.jar
      cleanup: true
      on:
        branch: main


    - provider: heroku 
      token: "$TOKEN_HEROKU"
      cleanup: true
      app: test-iv-kotlin
      on:
        all_branches: true
