# Especifica el SO y la distribución a usar
arch: amd64
os: linux
dist: xenial
language: java

# Especifica que se va a usar docker
services:
    - docker

# Descarga la imagen y la ejecuta
script:
    - docker run -t -v $TRAVIS_BUILD_DIR:/test rauldpm/test-iv-kotlin

after_success: true

#before_deploy:
#    if ! [[ $TRAVIS_TAG ]]; then
#        export TRAVIS_TAG="1.$TRAVIS_BUILD_NUMBER" &&
#        git config --local user.name "$USER_NAME" &&
#        git config --local user.email "$USER_EMAIL" &&
#        git tag "$TRAVIS_TAG";
#    fi


deploy:
    #- 
    #    provider: releases
    #    tag_name: $TRAVIS_TAG
    #    name: $TRAVIS_TAG
    #    cleanup: false
    #    api_key: "$TOKEN_GH"
    #    overwrite: true
    #    file: app/build/libs/app.jar
    #    on:
    #        branch: main

    -
        provider: heroku 
        skip_cleanup: true
        api_key: "$TOKEN_HEROKU"
        app: test-iv-kotlin
        on:
            branch: master


