/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.8-rc-4/userguide/building_java_projects.html
 */

import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar


plugins {
    id("org.jetbrains.kotlin.jvm") version "1.4.20"
    id("com.github.johnrengelman.shadow") version "6.1.0"
    application
}

repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:29.0-jre")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // Framework web
    implementation("io.ktor:ktor-server-netty:1.4.3")
    
}

application {
    // Define the main class for the application.
    //mainClass.set("Heroku.Kotlin.MainKt") // Este metodo es actualizado pero no compatible con shadowJar fatJar
    mainClassName = "Heroku.Kotlin.MainKt" // Este metodo es deprecado pero necesario para shadowJar fatJar
}

// Para crear el manifiesto del .jar
tasks.jar {
    manifest {
        attributes (
            "Main-Class" to "Heroku.Kotlin.MainKt"
        )
    }
}

// Para establecer un nombre personalizado al .jar
tasks.withType<ShadowJar>{ 
    archiveFileName.set("app.jar")
}
