/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package Heroku.Kotlin

import io.ktor.application.*
import io.ktor.features.*
import io.ktor.http.*
import io.ktor.response.*
import io.ktor.routing.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*
import io.ktor.request.*


fun Application.module() {
    install(DefaultHeaders)
    install(StatusPages) {
        exception<Throwable> {
            cause -> call.respond(HttpStatusCode.InternalServerError)
            throw cause 
        }
    }
    install(Routing) {
        app() 
    }
}

fun Route.app() {

    route("/") {
        
        get {
            try {
                call.response.status(HttpStatusCode.OK)
                call.respondText("Despliegue funcionando !!")
            } 
            catch (e : Exception) {
                call.response.status(HttpStatusCode.InternalServerError)
                call.respondText("Excepcion '" + e + "'")
            }
        }
    }
}

fun main() {
    embeddedServer(Netty, 8080, watchPaths = listOf("MainKt"), module = Application::module).start()
}
