
name: GHCR 

# Salta cuando hay un push a la rama master
on:
  push:
    branches:
      - main

# Trabajos a realizar
jobs:
  push:
    # Especifica la version del so
    runs-on: ubuntu-latest

    # Cuando es un push
    if: github.event_name == 'push'

    # Pasos del trabajo
    steps:

      - 
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Docker buildx
        uses: docker/setup-buildx-action@v1

      # Realiza el login a ghcr.io
      -
        name: LOGIN
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login ghcr.io -u ${{ secrets.DOCKER_USER }} --password-stdin

      # Realiza el build y push
      -
        name: BUILD and PUSH
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/rauldpm/test-iv-kotlin/test-iv-kotlin-con:latest
          push: true
