
name: heroku

on:
  push:
    branches:
        - main

jobs:
  deploy:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:

      # Realiza el login 
      - uses: actions/checkout@v2
      - 
        name: Login to Heroku
        run: (echo "${{secrets.HEROKU_EMAIL}}"; sleep 1; echo "${{ secrets.HEROKU_TOKEN }}"; ) | heroku login -i

      # Build and Deploy
      - 
        name: Build and Deploy
        run: "gradle build deployHeroku"
