
name: heroku

on:
  push:
    branches:
        - main

jobs:
  deploy:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:

      - 
        name: Checkout
        uses: actions/checkout@v2

      # Realiza el login 
      - 
        name: Login to Heroku
        env:
            HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN }}
        run: heroku login

      # Build and Deploy
      - 
        name: Build and Deploy
        run: "gradle build deployHeroku"
