
name: heroku

on:
  push:
    branches:
        - main

jobs:
  deploy:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:

      # Realiza el login 
      - uses: actions/checkout@v1
      - 
        name: Login to Heroku
        env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku login

      # Build and Deploy
      - 
        name: Build and Deploy
        run: "gradle build deployHeroku"
