
name: Deploy To Heroku

on:
  push:
    branches:
        - main

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
        - uses: actions/checkout@v2
        - name: Login
          env:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          run: heroku login

        - name: Deploy
          env:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          run: "ls && gradle build deployHeroku"